# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identifying the putative friend entity for the vector of ranks of the feature in different entities.
#'
#' @param x the list of ranks normalised to 0..1 -- in null, they are independently distributed
#' 
#' @return a vector of: index of the best, the best rank-the next rank and the p-value (it is the difference^n)
rank_diff_and_p <- function(x) {
    .Call('_best_friends_of_rank_diff_and_p', PACKAGE = 'best.friends.of', x)
}

