# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rank_diff_and_p_for_the_best <- function(x) {
    .Call(`_best_friends_rank_diff_and_p_for_the_best`, x)
}

rank_diff_and_p_for_the_best_n <- function(x, n = -1L) {
    .Call(`_best_friends_rank_diff_and_p_for_the_best_n`, x, n)
}

