// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rank_diff_and_p_for_the_best
NumericVector rank_diff_and_p_for_the_best(NumericVector x);
RcppExport SEXP _best_friends_rank_diff_and_p_for_the_best(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rank_diff_and_p_for_the_best(x));
    return rcpp_result_gen;
END_RCPP
}
// rank_diff_and_p_for_the_best_n
List rank_diff_and_p_for_the_best_n(NumericVector x, int max_num_friends);
RcppExport SEXP _best_friends_rank_diff_and_p_for_the_best_n(SEXP xSEXP, SEXP max_num_friendsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type max_num_friends(max_num_friendsSEXP);
    rcpp_result_gen = Rcpp::wrap(rank_diff_and_p_for_the_best_n(x, max_num_friends));
    return rcpp_result_gen;
END_RCPP
}
